// Balances every Journey level with the goal-aware bot and writes src/core/journeyTable.ts.
// `npm run journey:calibrate` (slow, a few minutes). Re-run after changing level design or rules.
//
// For each level the bot plays many attempts with no move limit. The move budget is the number
// of moves the bot needed in a chosen share of its attempts: 90 % on the first ten levels, falling
// from 85 % to 50 % by the last (so later levels need good play, or the +5 moves). A layout the bot can't beat
// often enough (the board jams) is replaced by the next variant. Stars: 2★ = the median winning
// score with the moves bonus, 3★ = the top 15 %.
import { writeFileSync } from 'node:fs';
import { describe, it } from 'vitest';
import { JOURNEY } from '../../src/config';
import { designLevel, movesBonus } from '../../src/core/journey';
import { playLevel } from './journeyBot';

const TRIES = Number(process.env.TRIES ?? 40);
const VARIANTS = 8;
const MAX_MOVES = 40;

const quantile = (sorted: number[], q: number): number =>
  sorted[Math.min(sorted.length - 1, Math.max(0, Math.ceil(q * sorted.length) - 1))] ?? Infinity;
const round10 = (x: number): number => Math.max(10, Math.round(x / 10) * 10);

describe('journey calibration', () => {
  it('writes the level table', () => {
    const table: [number, number, number, number][] = [];
    const report: string[] = [];
    for (let n = 1; n <= JOURNEY.levels; n++) {
      const d = (n - 1) / (JOURNEY.levels - 1);
      const share = n <= 10 ? 0.9 : 0.85 - 0.35 * d;
      let chosen: [number, number, number, number] | null = null;
      for (let v = 0; v < VARIANTS && !chosen; v++) {
        const spec = designLevel(n, v);
        const tries = Array.from({ length: TRIES }, (_, t) =>
          playLevel(spec, 7001 + t * 13 + n * 97 + v * 5, 2),
        );
        const used = tries.map((a) => (a.won ? a.used : Infinity)).sort((a, b) => a - b);
        const need = quantile(used, share);
        if (!Number.isFinite(need) || need > MAX_MOVES) continue;
        const moves = Math.max(JOURNEY.minMoves, need);
        const finals = tries
          .filter((a) => a.won && a.used <= moves)
          .map((a) => a.score + movesBonus(moves - a.used))
          .sort((a, b) => a - b);
        const s2 = round10(quantile(finals, 0.5));
        const s3 = Math.max(s2 + 10, round10(quantile(finals, 0.85)));
        chosen = [v, moves, s2, s3];
        report.push(
          `${String(n).padStart(3)} v${v} moves ${String(moves).padStart(2)} ★★ ${s2} ★★★ ${s3}  ` +
            `${spec.goals.map((g) => `${g.kind}:${g.target}`).join(' ')}  bot-wins ${((used.filter(Number.isFinite).length / TRIES) * 100).toFixed(0)}%`,
        );
      }
      if (!chosen) {
        chosen = [0, MAX_MOVES, 400, 800];
        report.push(`${String(n).padStart(3)} FALLBACK`);
      }
      table.push(chosen);
    }
    writeFileSync(
      'src/core/journeyTable.ts',
      `// Generated by \`npm run journey:calibrate\` (tests/sim/journey-calibrate.sim.ts). Do not edit by hand.\n` +
        `// Per level: [layout variant, moves, 2-star score, 3-star score].\n` +
        `export const LEVEL_TABLE: readonly (readonly [number, number, number, number])[] = [\n` +
        table.map((r) => `  [${r.join(', ')}],`).join('\n') +
        `\n];\n`,
    );
    writeFileSync('shots/journey-calibration.txt', report.join('\n'));
  });
});
